# -*- coding: utf-8 -*-
"""demo asr wav2vec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I8DJPLofd2RGFzW2AKto6CkEZIL6KwQl
"""



"""**هێنانی کتێبخانەی بەکار هاتوو**"""

from IPython.display import Audio
from scipy.io import wavfile
import numpy as np

file_name='/content/2.wav'

Audio(file_name)

"""** نیشاندانی کات و سامپڵ رێیت  **"""

data = wavfile.read(file_name)
framerate = data[0]
sounddata = data[1]
time = np.arange(0,len(sounddata))/framerate
print('Sample rate:',framerate,'Hz')
print('Total time:',len(sounddata)/framerate,'s')

"""دابەزاندنی مۆدێڵێ زمانی کوردی """

!pip install -q transformers 

import soundfile as sf
import librosa
import torch
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("Akashpb13/Central_kurdish_xlsr")
model = Wav2Vec2ForCTC.from_pretrained("Akashpb13/Central_kurdish_xlsr")

"""ناردنی فایلی دەنگی بۆ مۆدێلەکە و وەرگتنەوەی نوسین واتە گۆرینی بۆ **نوسین** """

input_audio, _ = librosa.load(file_name, 
                              sr=16000)
input_values = tokenizer(input_audio, return_tensors="pt").input_values
logits = model(input_values).logits
predicted_ids = torch.argmax(logits, dim=-1)
transcription = tokenizer.batch_decode(predicted_ids)[0]

transcription

